version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_dc_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # Параметры подключения к базе данных – они должны совпадать с настройками в config.json
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: cms_dc_dev
      # Параметры для JWT
      JWT_SECRET: "your_jwt_secret_key"
      JWT_EXPIRES_IN: "1h"
      JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"
      JWT_REFRESH_EXPIRES_IN: "7d"
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
