version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_dc_dev
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

  app:
    build: .
    restart: always
    container_name: app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: cms_dc_dev
      JWT_SECRET: "your_jwt_secret_key"
      JWT_EXPIRES_IN: "1h"
      JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"
      JWT_REFRESH_EXPIRES_IN: "7d"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["./wait-for-it.sh", "db:3306", "--", "node", "src/app.js"]
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    external: true
